apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-splunk
  name: monitoring-splunk
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: hec
    port: 8088
    targetPort: 8088
  - name: splunk-web
    port: 8000
    targetPort: 8000
  selector:
    name: monitoring-splunk
