apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-splunk
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: splunk
    spec:
      containers:
      - name: splunk
        image: splunk/splunk-monitoring:6.5.0
